Updated punctuations
sbmueller/nohello pull request #6
Opened 2022-02-14 06:28 UTC by kannansuresh

Updated punctuation and some phrasing.

2022-03-26 19:34 UTC, KTibow approved these changes

2022-03-27 08:52 UTC, sbmueller requested changes
Hi, sorry for my late reply.
The only improvements I see in this PR are one wording change and one capitalization change. I'm fine merging those. The other changes, I am not convinced they are necessary.

2022-03-27 08:52 UTC, sbmueller commented on _config.yml
> +theme: jekyll-theme-modernist
Please don't change the theme - it is intentionally kept simple and neutral. Themes are always subjective so I'm not open to discuss theme changes.

2022-03-27 08:52 UTC, sbmueller commented on index.md
> +Modern chat communication should be done in a way that saves time for all participants and enables an efficient, asynchronous exchange of information. Don’t expect an answer if you just write “Hello”
Please keep the line wrap at 79 characters. This helps readability in plain text. Without wrap, horizontal *and* vertical scrolling as well as more eye movement is necessary.

2022-03-27 08:52 UTC, sbmueller commented on index.md
> +It’s as if you called someone on the phone and said “Hi!” and then put them on hold!
I'm not sure why to replace all `"` by `“`. The former is valid punctuation. I reckon it is more difficult to incorporate follow-up changes when sticking to this convention, so I'd rather reject it. Also applies to all the other changes in this PR.

2022-03-28 02:50 UTC, kannansuresh commented
This was not intentional. This pull request was placed by mistake. Sorry for the inconvenience.

2022-03-28 02:50 UTC, closed without merging